-- Seed Crypto Affiliate Programs listings
INSERT INTO listings (category_id, slug, name, tagline, description, logo_url, website_url, affiliate_url, affiliate_commission, pricing_type, overall_rating, review_count, is_featured, is_verified, pros, cons) VALUES
((SELECT id FROM categories WHERE slug='crypto-affiliate-programs'),
  'binance-affiliate',
  'Binance Affiliate Program',
  'Earn up to 50% commission on trading fees',
  'Binance offers one of the most lucrative affiliate programs in crypto. Earn commissions on every trade your referrals make, with competitive rates and real-time tracking. The program includes marketing materials, dedicated support, and performance incentives for top affiliates.',
  'https://cryptologos.cc/logos/binance-coin-bnb-logo.png',
  'https://www.binance.com',
  'https://www.binance.com/en/affiliate',
  'Up to 50%',
  'free',
  4.7,
  1850,
  true,
  true,
  ARRAY['Up to 50% commission', 'Lifetime referral tracking', 'Real-time analytics dashboard', 'Multi-tier sub-affiliate program', 'Marketing materials provided', 'Dedicated affiliate support'],
  ARRAY['KYC required for affiliates', 'Minimum payout threshold', 'Commission varies by region']),

((SELECT id FROM categories WHERE slug='crypto-affiliate-programs'),
  'coinbase-affiliate',
  'Coinbase Affiliate Program',
  'Earn commissions by referring users to the most trusted US exchange',
  'Coinbase offers a straightforward affiliate program perfect for reaching US-based audiences. Get paid for every new user who signs up and completes their first trade. Trusted brand with strong conversion rates for beginner audiences.',
  'https://cryptologos.cc/logos/coinbase-symbol.png',
  'https://www.coinbase.com',
  'https://www.coinbase.com/affiliate',
  'Up to 50% of fees',
  'free',
  4.5,
  920,
  false,
  true,
  ARRAY['Trusted US-regulated brand', 'High conversion for beginners', 'Simple referral process', 'Monthly payouts', 'Coinbase marketing assets'],
  ARRAY['Limited to certain countries', 'Lower cookie duration', 'Stricter compliance requirements']),

((SELECT id FROM categories WHERE slug='crypto-affiliate-programs'),
  'kraken-affiliate',
  'Kraken Affiliate Program',
  'Partner with one of the most secure exchanges in crypto',
  'Kraken affiliate program rewards you for introducing users to their secure, feature-rich trading platform. Competitive commissions with a reputation-focused brand that resonates with security-conscious audiences.',
  'https://cryptologos.cc/logos/kraken-logo.png',
  'https://www.kraken.com',
  'https://www.kraken.com/affiliates',
  'Up to 50%',
  'free',
  4.6,
  680,
  false,
  true,
  ARRAY['Strong security reputation', 'Good for intermediate traders', 'Transparent fee structure', 'Professional affiliate support', 'Fiat onboarding available'],
  ARRAY['Smaller user base than competitors', 'Longer approval process', 'Limited promotional periods']),

((SELECT id FROM categories WHERE slug='crypto-affiliate-programs'),
  'bybit-affiliate',
  'Bybit Partner Program',
  'Earn lucrative rewards from derivatives trading referrals',
  'Bybit offers a partner program with some of the highest commissions in the industry, especially for derivatives trading. Great for audiences interested in leverage, perpetuals, and advanced trading strategies.',
  'https://cryptologos.cc/logos/bybit-logo.png',
  'https://www.bybit.com',
  'https://www.bybit.com/affiliate',
  'Up to 50%',
  'free',
  4.4,
  1100,
  false,
  true,
  ARRAY['Highest derivatives commissions', 'No-KYC trading available', 'Multi-tier referral system', 'Weekly payouts available', 'Testnet for demos'],
  ARRAY['Not available in all regions', 'Complex for pure beginners', 'Regulatory uncertainty']),

((SELECT id FROM categories WHERE slug='crypto-affiliate-programs'),
  'kucoin-affiliate',
  'KuCoin Partner Program',
  'Monetize your audience with an altcoin-focused exchange',
  'KuCoin affiliate program is ideal for reaching altcoin enthusiasts. With 800+ tokens and strong appeal in emerging markets, you can earn commissions on trades from a diverse user base.',
  'https://cryptologos.cc/logos/kuccoin-logo.png',
  'https://www.kucoin.com',
  'https://www.kucoin.com/affiliate',
  'Up to 50%',
  'free',
  4.3,
  540,
  false,
  true,
  ARRAY['Massive altcoin selection', 'Strong in Asia markets', 'Multiple payout options', 'Marketing resources included', 'Sub-affiliate earnings'],
  ARRAY['Lower brand recognition in West', 'Variable liquidity on pairs', 'Complex fee structure']),

((SELECT id FROM categories WHERE slug='crypto-affiliate-programs'),
  'ledger-affiliate',
  'Ledger Affiliate Program',
  'Earn commissions promoting the most popular hardware wallet',
  'Ledger affiliate program lets you earn by promoting their industry-leading hardware wallets. Great for content creators focused on security education and cold storage solutions.',
  'https://cryptologos.cc/logos/ledger-logo.png',
  'https://www.ledger.com',
  'https://www.ledger.com/affiliate',
  'Up to 15%',
  'free',
  4.5,
  420,
  true,
  true,
  ARRAY['Industry-leading product', 'Strong conversion rates', 'High ticket value', 'Educational content support', 'Global shipping available'],
  ARRAY['Lower commission percentage', 'Seasonal sales focus', 'Hardware inventory issues']),

((SELECT id FROM categories WHERE slug='crypto-affiliate-programs'),
  'trezor-affiliate',
  'Trezor Affiliate Program',
  'Partner with the original hardware wallet pioneer',
  'Trezor offers an affiliate program for their open-source hardware wallets. Ideal for audiences who value transparency and security-first principles in their crypto storage.',
  'https://cryptologos.cc/logos/trezor-logo.png',
  'https://trezor.io',
  'https://trezor.io/affiliates',
  'Up to 12%',
  'free',
  4.2,
  280,
  false,
  true,
  ARRAY['Open-source hardware', 'Strong security reputation', 'Quality educational materials', 'Good for privacy advocates'],
  ARRAY['Lower commission than competitors', 'Fewer marketing resources', 'Smaller product range']),

((SELECT id FROM categories WHERE slug='crypto-affiliate-programs'),
  'koinly-affiliate',
  'Koinly Affiliate Program',
  'Earn by helping users solve their crypto tax headaches',
  'Koinly affiliate program targets the pain point of crypto tax reporting. High conversion during tax season with a product that genuinely helps users save on accounting costs.',
  'https://cryptologos.cc/logos/koinly-logo.png',
  'https://koinly.io',
  'https://koinly.io/affiliates',
  '25%',
  'free',
  4.6,
  350,
  false,
  true,
  ARRAY['Solves real pain point', 'High seasonal demand', 'Generous commission rate', 'Strong product-market fit', 'Multiple integrations'],
  ARRAY['Seasonal traffic spikes', 'Limited appeal outside tax season', 'Niche audience']),

((SELECT id FROM categories WHERE slug='crypto-affiliate-programs'),
  '3commas-affiliate',
  '3Commas Affiliate Program',
  'Earn from trading bot referrals with recurring commissions',
  '3Commas offers an affiliate program for their automated trading platform. Great for audiences interested in algorithmic trading, DCA strategies, and portfolio management tools.',
  'https://cryptologos.cc/logos/3commas-logo.png',
  'https://3commas.io',
  'https://3commas.io/affiliate',
  'Up to 30%',
  'free',
  4.1,
  220,
  false,
  true,
  ARRAY['Recurring commissions', 'Strong trading audience', 'Multi-exchange support', 'Webinars and demos available'],
  ARRAY['Complex product to explain', 'Recent security incident history', 'Smaller addressable market']),

((SELECT id FROM categories WHERE slug='crypto-affiliate-programs'),
  'ledger-referral',
  'Ledger Referral Program',
  'Direct referral rewards for Ledger sales',
  'Ledger referral program offers an alternative to their main affiliate program with simpler terms. Earn by recommending Ledger devices directly to your community.',
  'https://cryptologos.cc/logos/ledger-logo.png',
  'https://www.ledger.com',
  'https://www.ledger.com/referral',
  '10%',
  'free',
  3.9,
  180,
  false,
  false,
  ARRAY['Simple to join', 'No minimum threshold', 'Fast payouts', 'Trusted brand'],
  ARRAY['Lower commissions', 'Limited tracking', 'Basic reporting tools']);