-- Seed realistic promotions
INSERT INTO promotions (listing_id, title, description, bonus_value, promo_code, starts_at, expires_at, is_active) VALUES
-- Exchange promotions
((SELECT id FROM listings WHERE slug = 'binance'), 
 'Sign-Up Bonus', 
 'Get $50 in BTC when you sign up and complete your first trade of $100 or more within 7 days.',
 '$50 in BTC', 
 NULL, 
 NOW() - INTERVAL '30 days', 
 NOW() + INTERVAL '60 days', 
 TRUE),

((SELECT id FROM listings WHERE slug = 'coinbase'), 
 'Earn $10 in Bitcoin', 
 'Earn $10 in BTC when you sign up and buy or sell $100 of crypto.',
 '$10 in BTC', 
 NULL, 
 NOW() - INTERVAL '15 days', 
 NULL, 
 TRUE),

((SELECT id FROM listings WHERE slug = 'kraken'), 
 'Zero Trading Fees', 
 'Enjoy 0% maker fees for your first 30 days of trading.',
 '0% fees for 30 days',
 'KRAKEN30',
 NOW(), 
 NOW() + INTERVAL '45 days', 
 TRUE),

((SELECT id FROM listings WHERE slug = 'bybit'), 
 'Deposit Bonus', 
 'Deposit $200 or more and receive a $20 USDT bonus instantly.',
 '$20 USDT',
 'BYBITDEPOSIT',
 NOW(), 
 NOW() + INTERVAL '30 days', 
 TRUE),

-- Wallet promotions
((SELECT id FROM listings WHERE slug = 'ledger-nano-x'), 
 '10% Off Ledger Nano X', 
 'Get 10% off the Ledger Nano X hardware wallet with this exclusive code.',
 '10% off',
 'LEDGER10',
 NOW() - INTERVAL '10 days', 
 NOW() + INTERVAL '20 days', 
 TRUE),

((SELECT id FROM listings WHERE slug = 'trezor-model-t'), 
 'Free Shipping', 
 'Free worldwide shipping on Trezor Model T orders over $150.',
 'Free shipping',
 NULL, 
 NOW(), 
 NOW() + INTERVAL '14 days', 
 TRUE),

-- Tax software promotions
((SELECT id FROM listings WHERE slug = 'koinly'), 
 '20% Off Annual Plan', 
 'Save 20% on your Koinly annual subscription with our exclusive discount.',
 '20% off',
 'KOINLY20',
 NOW(), 
 NOW() + INTERVAL '60 days', 
 TRUE),

((SELECT id FROM listings WHERE slug = 'cointracker'), 
 'Free Tax Report', 
 'New users get their first tax report free (up to 100 transactions).',
 '1 free report',
 NULL, 
 NOW() - INTERVAL '20 days', 
 NOW() + INTERVAL '90 days', 
 TRUE),

-- Trading bot promotions
((SELECT id FROM listings WHERE slug = '3commas'), 
 '50% Off First Month', 
 'Get 50% off your first month of any 3Commas subscription plan.',
 '50% off first month',
 '3COMMAS50',
 NOW(), 
 NOW() + INTERVAL '30 days', 
 TRUE),

((SELECT id FROM listings WHERE slug = 'pionex'), 
 'No Trading Fees + Bonus', 
 'Zero fees on grid trading bots for your first 30 days.',
 '0% bot fees for 30 days',
 NULL, 
 NOW(), 
 NULL, 
 TRUE);