-- Add listing attributes for filtering (enables programmatic SEO pages)
-- Crypto Exchange attributes
INSERT INTO listing_attributes (listing_id, attribute_key, attribute_value) VALUES
((SELECT id FROM listings WHERE slug='binance'), 'beginner_friendly', 'true'),
((SELECT id FROM listings WHERE slug='binance'), 'supports_staking', 'true'),
((SELECT id FROM listings WHERE slug='binance'), 'has_mobile_app', 'true'),
((SELECT id FROM listings WHERE slug='binance'), 'kyc_required', 'true'),
((SELECT id FROM listings WHERE slug='binance'), 'fiat_support', 'true'),
((SELECT id FROM listings WHERE slug='binance'), 'dex_available', 'true'),
((SELECT id FROM listings WHERE slug='coinbase'), 'beginner_friendly', 'true'),
((SELECT id FROM listings WHERE slug='coinbase'), 'supports_staking', 'true'),
((SELECT id FROM listings WHERE slug='coinbase'), 'has_mobile_app', 'true'),
((SELECT id FROM listings WHERE slug='coinbase'), 'kyc_required', 'true'),
((SELECT id FROM listings WHERE slug='coinbase'), 'fiat_support', 'true'),
((SELECT id FROM listings WHERE slug='kraken'), 'beginner_friendly', 'false'),
((SELECT id FROM listings WHERE slug='kraken'), 'supports_staking', 'true'),
((SELECT id FROM listings WHERE slug='kraken'), 'has_mobile_app', 'true'),
((SELECT id FROM listings WHERE slug='kraken'), 'kyc_required', 'true'),
((SELECT id FROM listings WHERE slug='kraken'), 'fiat_support', 'true'),
((SELECT id FROM listings WHERE slug='kraken'), 'margin_trading', 'true'),
((SELECT id FROM listings WHERE slug='bybit'), 'beginner_friendly', 'false'),
((SELECT id FROM listings WHERE slug='bybit'), 'supports_staking', 'true'),
((SELECT id FROM listings WHERE slug='bybit'), 'has_mobile_app', 'true'),
((SELECT id FROM listings WHERE slug='bybit'), 'kyc_required', 'false'),
((SELECT id FROM listings WHERE slug='bybit'), 'fiat_support', 'false'),
((SELECT id FROM listings WHERE slug='bybit'), 'margin_trading', 'true'),
((SELECT id FROM listings WHERE slug='kucoin'), 'beginner_friendly', 'true'),
((SELECT id FROM listings WHERE slug='kucoin'), 'supports_staking', 'true'),
((SELECT id FROM listings WHERE slug='kucoin'), 'has_mobile_app', 'true'),
((SELECT id FROM listings WHERE slug='kucoin'), 'kyc_required', 'false'),
((SELECT id FROM listings WHERE slug='kucoin'), 'fiat_support', 'true'),
((SELECT id FROM listings WHERE slug='gemini'), 'beginner_friendly', 'true'),
((SELECT id FROM listings WHERE slug='gemini'), 'supports_staking', 'true'),
((SELECT id FROM listings WHERE slug='gemini'), 'has_mobile_app', 'true'),
((SELECT id FROM listings WHERE slug='gemini'), 'kyc_required', 'true'),
((SELECT id FROM listings WHERE slug='gemini'), 'fiat_support', 'true');

-- Hardware Wallet attributes
INSERT INTO listing_attributes (listing_id, attribute_key, attribute_value) VALUES
((SELECT id FROM listings WHERE slug='ledger-nano-x'), 'bluetooth', 'true'),
((SELECT id FROM listings WHERE slug='ledger-nano-x'), 'coin_count', '5500'),
((SELECT id FROM listings WHERE slug='ledger-nano-x'), 'usb_type', 'USB-C'),
((SELECT id FROM listings WHERE slug='ledger-nano-x'), 'open_source', 'false'),
((SELECT id FROM listings WHERE slug='ledger-nano-x'), 'mobile_support', 'true'),
((SELECT id FROM listings WHERE slug='trezor-model-t'), 'bluetooth', 'false'),
((SELECT id FROM listings WHERE slug='trezor-model-t'), 'coin_count', '1800'),
((SELECT id FROM listings WHERE slug='trezor-model-t'), 'usb_type', 'USB-C'),
((SELECT id FROM listings WHERE slug='trezor-model-t'), 'open_source', 'true'),
((SELECT id FROM listings WHERE slug='trezor-model-t'), 'mobile_support', 'false'),
((SELECT id FROM listings WHERE slug='trezor-one'), 'bluetooth', 'false'),
((SELECT id FROM listings WHERE slug='trezor-one'), 'coin_count', '1000'),
((SELECT id FROM listings WHERE slug='trezor-one'), 'usb_type', 'micro-USB'),
((SELECT id FROM listings WHERE slug='trezor-one'), 'open_source', 'true'),
((SELECT id FROM listings WHERE slug='trezor-one'), 'mobile_support', 'false'),
((SELECT id FROM listings WHERE slug='ledger-nano-s-plus'), 'bluetooth', 'false'),
((SELECT id FROM listings WHERE slug='ledger-nano-s-plus'), 'coin_count', '5500'),
((SELECT id FROM listings WHERE slug='ledger-nano-s-plus'), 'usb_type', 'USB-C'),
((SELECT id FROM listings WHERE slug='ledger-nano-s-plus'), 'open_source', 'false'),
((SELECT id FROM listings WHERE slug='ledger-nano-s-plus'), 'mobile_support', 'false'),
((SELECT id FROM listings WHERE slug='safe-pal'), 'bluetooth', 'false'),
((SELECT id FROM listings WHERE slug='safe-pal'), 'coin_count', '10000'),
((SELECT id FROM listings WHERE slug='safe-pal'), 'usb_type', 'none'),
((SELECT id FROM listings WHERE slug='safe-pal'), 'open_source', 'false'),
((SELECT id FROM listings WHERE slug='safe-pal'), 'mobile_support', 'true'),
((SELECT id FROM listings WHERE slug='safe-pal'), 'air_gapped', 'true');